sudo: false
dist: bionic
language: generic

cache:
  directories:
  - $HOME/.stack
  - $HOME/.local/bin

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - mkdir -p ~/tmp
  - travis_retry eval $"sudo apt-get update ; sleep 10"
  - travis_retry eval $"sudo apt-get install --yes libgmp-dev haskell-stack ; sleep 10"
  - if [ ! -d "$DIR" ]; then mkdir -p ~/.local/bin; fi
  - travis_retry eval $"stack upgrade --binary-only ; sleep 10"
  - export PATH=~/.local/bin:$PATH
  - hash -r
  - stack --version

matrix:
  include:
    - env: GHCVER=8.0.2 STACK_YAML=stack-8.0.2.yaml
      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}
    - env: GHCVER=8.2.2 STACK_YAML=stack-8.2.2.yaml
      addons: {apt: {packages: [ghc-8.2.2],sources: [hvr-ghc]}}
    - env: GHCVER=8.4.2 STACK_YAML=stack-8.4.2.yaml
      addons: {apt: {packages: [ghc-8.4.2],sources: [hvr-ghc]}}
    - env: GHCVER=8.6.2 STACK_YAML=stack-8.6.2.yaml
      addons: {apt: {packages: [ghc-8.6.2],sources: [hvr-ghc]}}
    - env: GHCVER=8.8.4 STACK_YAML=stack-8.8.4.yaml
      addons: {apt: {packages: [ghc-8.8.4],sources: [hvr-ghc]}}

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check install happy alex

script:
  - rm -f stack.yaml
  - cp -f $STACK_YAML stack.yaml
  - make test
